#!/bin/bash

clear
echo -e "                                                        "
echo -e "\e[94m         _|_|_|    _|    _|    _|_|_|                      _|            "
echo -e "\e[94m         _|    _|  _|    _|  _|          _|_|_|  _|  _|_|  _|          "
echo -e "\e[94m         _|_|_|    _|_|_|_|  _|        _|    _|  _|_|      _|          "
echo -e "\e[94m         _|        _|    _|  _|        _|    _|  _|        _|              "
echo -e "\e[94m         _|        _|    _|    _|_|_|    _|_|_|  _|        _|            "
echo -e "\e[94m.  ---------------------------------------------------------------      "
echo -e "\e[94m         OCS Panel Template by PHCarl         "
echo -e "\e[94m                                                  "
echo -e "\e[94m     Do you Really want to install this OCS Panel Template?    "
echo -e "\e[94m        1) Yes                    "
echo -e "\e[94m        2) No                  "
echo -e "\e[94m                                                  "
read -p "     Select an option [1-2]: " option
  case $option in
        1)
        clear
        wget https://raw.githubusercontent.com/PHCarl10/PHCarlOCS/master/PHCarl_OCS
        chmod +x PHCarl_OCS
        ./PHCarl_OCS
        exit
        ;;
        2)
        clear
        exit
        ;;
  esac
